#!/usr/bin/env bash

# Validate commit log
commit_regex='^Merge.+|(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert|types)(\(.+\))?: .{1,50}'

if ! grep -iqE "$commit_regex" "$1"; then
    echo
    echo "  错误：自动生成变更日志需要正确的提交消息格式。"
    echo
    echo "  - 运用 \`npm run commit\` 来交互式生成提交消息"
    echo
    exit 1
fi
